from datetime import datetime
from generator.roadmap import Roadmap
from generator.timelinemode import TimelineMode


def demo01(
    mode: TimelineMode = TimelineMode.MONTHLY,
    start_date: str = "2023-01-01",
    number_of_items: int = 12,
    file_name: str = "demo01.png",
) -> None:
    roadmap = Roadmap(1200, 312)
    roadmap.set_title("My Demo Roadmap")
    roadmap.set_timeline(mode, start_date, number_of_items)
    with roadmap.add_group("Core Product Work Stream") as group:
        with group.add_task("Base Functionality", "2022-11-01", "2023-10-31") as task:
            task.add_milestone("v.1.0", "2023-02-15")
            task.add_milestone("v.1.1", "2023-08-01")
            task.add_milestone("v.1.2", "2023-09-30")
            with task.add_parellel_task(
                "Enhancements", "2023-11-15", "2024-03-31"
            ) as task1a:
                task1a.add_milestone("v.2.0", "2024-03-30")
        with group.add_task("Showcase #1", "2023-03-01", "2023-05-07") as task:
            with task.add_parellel_task(
                "Showcase #2", "2023-06-01", "2023-08-07"
            ) as parellel_task:
                pass

    with roadmap.add_group("Mobility Work Stream") as group:
        with group.add_task(
            "Mobile App Development", "2023-02-01", "2024-12-07"
        ) as task:
            task.add_milestone("iOS App", "2023-04-15")
            task.add_milestone("Android App", "2023-09-07")

    roadmap.set_footer("Generated by Roadmap Generator")
    roadmap.draw()
    roadmap.save(file_name)


def demo02(
    mode: TimelineMode = TimelineMode.MONTHLY,
    start_date: str = "2023-01-01",
    number_of_items: int = 12,
    file_name: str = "demo01.png",
) -> None:
    roadmap = Roadmap(1200, 312)
    roadmap.set_title(
        "My Demo Roadmap", font_colour="Salmon", font="Arial", font_size=28
    )
    roadmap.set_timeline(mode, start_date, number_of_items)
    with roadmap.add_group("Core Product Work Stream") as group:
        with group.add_task("Base Functionality", "2022-11-01", "2023-10-31") as task:
            task.add_milestone("v.1.0", "2023-02-15")
            task.add_milestone("v.1.1", "2023-08-01")
            task.add_milestone("v.1.2", "2023-09-30")
            with task.add_parellel_task(
                "Enhancements", "2023-11-15", "2024-03-31"
            ) as task1a:
                task1a.add_milestone("v.2.0", "2024-03-30")
        with group.add_task("Showcase #1", "2023-03-01", "2023-05-07") as task:
            with task.add_parellel_task(
                "Showcase #2", "2023-06-01", "2023-08-07"
            ) as parellel_task:
                pass

    with roadmap.add_group("Mobility Work Stream") as group:
        with group.add_task(
            "Mobile App Development", "2023-02-01", "2024-12-07"
        ) as task:
            task.add_milestone("iOS App", "2023-04-15")
            task.add_milestone("Android App", "2023-09-07")

    roadmap.set_footer("Generated by Roadmap Generator")
    roadmap.draw()
    roadmap.save(file_name)


demo01(file_name="demo01.png")
demo01(TimelineMode.WEEKLY, "2023-02-01", 16, "demo02.png")
demo01(TimelineMode.QUARTERLY, "2023-02-01", 4, "demo03.png")
demo01(TimelineMode.HALF_YEARLY, "2023-02-01", 3, "demo04.png")
demo01(TimelineMode.YEARLY, "2023-02-01", 2, "demo05.png")

demo02(file_name="demo06.png")
