from datetime import datetime
from roadmapper.roadmap import Roadmap
from roadmapper.timelinemode import TimelineMode


def debug01(
    timelinemode: TimelineMode = TimelineMode.MONTHLY,
    start_date: str = "2022-12-01",
    number_of_items: int = 26,
    show_generic_dates: bool = False,
    file_name: str = "demo01",
    colour_theme: str = "DEFAULT",
    painter_type: str = "PNG",
) -> None:
    roadmap = Roadmap(
        1200,
        1000,
        auto_height=True,
        colour_theme=colour_theme,
        show_marker=True,
        painter_type=painter_type,
    )
    roadmap.set_background_colour("lightblue")
    roadmap.add_logo("images/logo/matariki-tech-logo.png", "top-left", 50, 50)
    roadmap.set_title("SAMPLE ROADMAP 2022/2023")
    roadmap.set_subtitle("ABC Corporation")
    roadmap.set_timeline(
        timelinemode,
        start=start_date,
        number_of_items=number_of_items,
        show_generic_dates=show_generic_dates,
    )

    group = roadmap.add_group("Core Product Work Stream", text_alignment="left")
    task = group.add_task("Base Functionality", "2022-11-01", "2023-10-31")
    task.add_milestone("v.1.0", "2023-02-15")
    task.add_milestone("v.1.1", "2023-08-01")
    parellel_task = task.add_parallel_task("Enhancements", "2023-11-15", "2024-03-31")
    parellel_task.add_milestone("v.2.0", "2024-03-30")

    task = group.add_task("Showcase #1", "2023-03-01", "2023-05-07")
    task.add_parallel_task("Showcase #2", "2023-06-01", "2023-08-07")

    group = roadmap.add_group("Mobility Work Stream", text_alignment="left")
    group.add_task("Mobile App Development", "2023-02-01", "2024-12-07")

    roadmap.set_footer("Updated on " + datetime.now().strftime("%Y-%m-%d"))
    roadmap.draw()

    if painter_type == "SVG":
        file_name += ".svg"
    else:
        file_name += ".png"

    roadmap.save(file_name)


def debug02(
    timelinemode: TimelineMode = TimelineMode.MONTHLY,
    start_date: str = "2022-12-01",
    number_of_items: int = 26,
    show_generic_dates: bool = False,
    file_name: str = "demo02",
    colour_theme: str = "DEFAULT",
    painter_type: str = "PNG",
) -> None:
    roadmap = Roadmap(
        1200,
        1000,
        auto_height=True,
        colour_theme=colour_theme,
        show_marker=True,
        painter_type=painter_type,
    )
    roadmap.set_background_colour("lightblue")

    roadmap.set_title("Title")
    roadmap.set_timeline(TimelineMode.MONTHLY, start="2023-01-01", number_of_items=26)

    group = roadmap.add_group("Group")

    group.add_task("Task", "2023-01-01", "2024-12-31", fill_colour="#00FF00")

    roadmap.draw()

    if painter_type == "SVG":
        file_name += ".svg"
    else:
        file_name += ".png"

    roadmap.save(file_name)


def debug03():
    output_file = "debug03.png"

    my_roadmap = Roadmap(width=800, height=400)
    my_roadmap.set_title("My Roadmap")
    my_roadmap.set_timeline(
        mode=TimelineMode.MONTHLY, start="2023-07-01", number_of_items=12
    )

    group = my_roadmap.add_group("Development")
    group.add_task("Activity 1", "2023-09-01", "2024-02-10")
    group.add_task("Activity 2", "2024-01-11", "2024-03-20")
    group.add_task("Activity 3", "2024-01-21", "2024-06-30")

    my_roadmap.set_footer("Generated by Roadmapper")
    my_roadmap.draw()
    my_roadmap.save(output_file)


def debug04():
    output_file = "debug04.png"

    my_roadmap = Roadmap(width=800, height=400, show_marker=False)
    my_roadmap.set_title("My Roadmap")
    my_roadmap.set_timeline(
        mode=TimelineMode.MONTHLY, start="2024-01-01", number_of_items=6
    )

    group = my_roadmap.add_group("Development")
    task1 = group.add_task("Activity 1", "2024-01-01", "2024-03-10")
    task1.add_milestone("MS1", "2024-02-01", fill_colour="green", font_colour="red")
    group.add_task("Activity 2", "2024-01-11", "2024-03-20")

    my_roadmap.set_footer("Generated by Roadmapper")
    my_roadmap.draw()
    my_roadmap.save(output_file)

    
def debug04_svg():
    output_file = "debug04.svg"

    my_roadmap = Roadmap(width=800, height=400, show_marker=False, painter_type="svg")
    my_roadmap.set_title("My Roadmap")
    my_roadmap.set_timeline(
        mode=TimelineMode.MONTHLY, start="2024-01-01", number_of_items=6
    )

    group = my_roadmap.add_group("Development")
    task1 = group.add_task("Activity 1", "2024-01-01", "2024-03-10")
    task1.add_milestone("MS1", "2024-02-01", fill_colour="green", font_colour="red")
    group.add_task("Activity 2", "2024-01-11", "2024-03-20")

    my_roadmap.set_footer("Generated by Roadmapper")
    my_roadmap.draw()
    my_roadmap.save(output_file)


if __name__ == "__main__":
    # output_file = "debug01"
    # debug01(
    #     file_name=output_file,
    #     timelinemode=TimelineMode.MONTHLY,
    #     number_of_items=14,
    # )
    # output_file = "debug02"
    # debug02(
    #     file_name=output_file,
    #     timelinemode=TimelineMode.MONTHLY,
    #     number_of_items=14,
    # )
    # debug03()
    debug04()
    debug04_svg()
