from roadmapper.roadmap import Roadmap
from roadmapper.timelinemode import TimelineMode

roadmap = Roadmap(1200, 380, colour_theme="BLUEMOUNTAIN", show_marker=True)
roadmap.set_title("Product Roadmap")
roadmap.set_subtitle("Matariki Tech Ltd")
roadmap.set_timeline(TimelineMode.MONTHLY, "2023-01-01", 9)
roadmap.set_footer("Generated by Roadmapper")

group = roadmap.add_group("Workstream 1")
task = group.add_task("Task 1-A", "2023-01-01", "2023-05-15")
task.add_parallel_task("Task 2-B", "2023-05-16", "2023-08-30")
task = group.add_task("Task 3-C", "2023-04-01", "2023-06-30")
task.add_milestone("Milestone 1", "2023-06-30")


roadmap.draw()
roadmap.save("images/roadmapper-anatomy-base.png")
