from roadmapper.roadmap import Roadmap
from roadmapper.timelinemode import TimelineMode

roadmap = Roadmap(600, 380, colour_theme="BLUEMOUNTAIN", show_marker=True)
roadmap.set_title("My Demo Roadmap")
roadmap.set_timeline(TimelineMode.QUARTERLY, "2023-01-01", 4)
roadmap.set_footer("Generated by Roadmapper")

group = roadmap.add_group("Workstream 1")
task = group.add_task("Task 1-A", "2023-01-01", "2023-04-30")
task.add_parallel_task("Task 2-B", "2023-05-15", "2023-08-30")
group.add_task("Task 3-C", "2023-04-01", "2023-06-30")

group = roadmap.add_group("Workstream 2")
group.add_task("Task 2-A", "2023-04-01", "2023-06-30")
group.add_task("Task 2-B", "2023-05-01", "2023-07-30")
group.add_task("Task 2-C", "2023-06-01", "2023-08-30")

roadmap.draw()
roadmap.save("theme-demo01.png")
