from roadmapper.roadmap import Roadmap
from roadmapper.timelinemode import TimelineMode

roadmap = Roadmap(600, 500, show_marker=False, auto_height=True)
roadmap.set_title("My Demo Roadmap")
roadmap.set_timeline(
    TimelineMode.QUARTERLY,
    "2023-01-01",
    3,
    year_fill_colour="#7CC1AC",
    year_font_colour="black",
    item_fill_colour="#7CC1AC",
    item_font_colour="black",
)
roadmap.set_footer("Generated by Roadmapper")
group = roadmap.add_group(
    "Workstream 1", font_colour="black", fill_colour="#C38D9D", font_size=12
)
task = group.add_task(
    "Task 1-A", "2023-01-01", "2023-04-30", font_colour="black", fill_colour="#D7B3BD"
)
task.add_parallel_task(
    "Task 2-B", "2023-05-15", "2023-08-30", font_colour="black", fill_colour="#D7B3BD"
)
group.add_task(
    "Task 3-C", "2023-04-01", "2023-06-30", font_colour="black", fill_colour="#D7B3BD"
)

group = roadmap.add_group(
    "Workstream 2", font_colour="black", fill_colour="#E8A87C", font_size=12
)
group.add_task(
    "Task 2-A", "2023-04-01", "2023-06-30", font_colour="black", fill_colour="#EFC5A7"
)
group.add_task(
    "Task 2-B", "2023-05-01", "2023-07-30", font_colour="black", fill_colour="#EFC5A7"
)
group.add_task(
    "Task 2-C", "2023-06-01", "2023-08-30", font_colour="black", fill_colour="#EFC5A7"
)

roadmap.draw()
roadmap.save("demo01.png")
