name: Secret checker

on:
  push:
  pull_request:

jobs:
  checker:

    runs-on: ubuntu-latest

    steps:
      - name: "Check if PYPI_USERNAME exists"
        env:
          USERNAME: ${{ secrets.PYPI_USERNAME }}
        if: ${{ env.USERNAME == '' }}
        run: |
          echo "The secret \"PYPI_USERNAME\" has not been set."
          echo "Please go to \"settings \> secrets \> actions\" to create it."
      - name: "Check if PYPI_PASSWORD exists"
        env:
          PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        if: ${{ env.PASSWORD == '' }}
        run: |
          echo "The secret \"PYPI_PASSWORD\" has not been set."
          echo "Please go to \"settings \> secrets \> actions\" to create it."
